[package]
name = "rockfish"
version = "0.1.0"
edition = "2021"
authors = ["Syzygy", "SunnyWar"]

[profile.release] 
debug = true
strip = false

[dependencies]
lazy_static = "1.5.0"
memmap = "0.7.0"
ndarray = "0.16.1"
